-- Combined migrations: merged from individual migration files
-- Generated by assistant: ordered, deduplicated headers (single USE), kept original statements
-- Run this file against MySQL/MariaDB. It is idempotent where possible.

-- Version 001: Create database and users (admin) table, and seed Super Admin
CREATE DATABASE IF NOT EXISTS digital_signage
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_0900_ai_ci;

USE digital_signage;

-- 001_create_admin.sql
CREATE TABLE IF NOT EXISTS users (
  id            INT           NOT NULL AUTO_INCREMENT,
  employee_id   VARCHAR(50)   DEFAULT NULL,
  full_name     VARCHAR(100)  NOT NULL DEFAULT 'System Admin',
  username      VARCHAR(50)   NOT NULL,
  password      VARCHAR(255)  NOT NULL,
  role          ENUM('super_admin', 'normal_admin') NOT NULL,
  branch        ENUM('PBMH', 'SSCC', 'Dental') DEFAULT NULL,
  location      ENUM('A Block', 'B/C Block', 'KSS', 'KCC', 'Dental') DEFAULT NULL,
  created_at    TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY username (username),
  UNIQUE KEY employee_id (employee_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Default Super Admin (password: Admin@123)
INSERT IGNORE INTO users (id, username, password, role, full_name)
VALUES (1, 'Admin', '$2b$10$AvKt4enGMrEmgHMIM/8N7.joTYGdsq2BhSW0xHwCz1WcbasVUX1yy', 'super_admin', 'System Admin');

-- 002_create_locations.sql
CREATE TABLE IF NOT EXISTS branches_locations (
  id        INT          NOT NULL AUTO_INCREMENT,
  branch    VARCHAR(100) NOT NULL,
  location  VARCHAR(100) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_branch_location (branch, location)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Default Branch-Location pairs
INSERT IGNORE INTO branches_locations (branch, location) VALUES ('PBMH', 'A Block');
INSERT IGNORE INTO branches_locations (branch, location) VALUES ('PBMH', 'B/C Block');
INSERT IGNORE INTO branches_locations (branch, location) VALUES ('SSCC', 'KSS');
INSERT IGNORE INTO branches_locations (branch, location) VALUES ('SSCC', 'KCC');
INSERT IGNORE INTO branches_locations (branch, location) VALUES ('Dental', 'Dental');

-- 003_create_departments.sql
CREATE TABLE IF NOT EXISTS departments (
  id          INT          NOT NULL AUTO_INCREMENT,
  name        VARCHAR(100) NOT NULL,
  created_at  TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY name (name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- 004_create_doctors.sql
CREATE TABLE IF NOT EXISTS doctors (
  id              INT          NOT NULL AUTO_INCREMENT,
  employee_id     VARCHAR(50)  NOT NULL,
  name            VARCHAR(100) NOT NULL,
  designation     VARCHAR(100) NOT NULL,
  department_id   INT          NOT NULL,
  branch          VARCHAR(50)  NOT NULL,
  location        VARCHAR(100) NOT NULL,
  created_at      TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY employee_id (employee_id),
  CONSTRAINT doctors_ibfk_1 FOREIGN KEY (department_id) REFERENCES departments (id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- 005_create_displays.sql
CREATE TABLE IF NOT EXISTS displays (
  id      INT          NOT NULL AUTO_INCREMENT,
  name    VARCHAR(100) NOT NULL,
  branch  VARCHAR(50)  NOT NULL,
  location VARCHAR(100) NOT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- 006_create_schedules.sql
CREATE TABLE IF NOT EXISTS roster (
  id            INT          NOT NULL AUTO_INCREMENT,
  date          DATE         NOT NULL,
  employee_id   VARCHAR(50)  NOT NULL,
  timing        VARCHAR(100) NOT NULL,
  created_at    TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY unique_roster_entry (date, employee_id),
  CONSTRAINT roster_ibfk_1 FOREIGN KEY (employee_id) REFERENCES doctors (employee_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- 007_create_users.sql (user assignment/permissions tables)
CREATE TABLE IF NOT EXISTS user_branches (
  id        INT         NOT NULL AUTO_INCREMENT,
  user_id   INT         NOT NULL,
  branch    VARCHAR(50) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY unique_user_branch (user_id, branch),
  CONSTRAINT user_branches_ibfk_1 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS user_locations (
  id        INT          NOT NULL AUTO_INCREMENT,
  user_id   INT          NOT NULL,
  branch    VARCHAR(50)  NOT NULL,
  location  VARCHAR(100) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY unique_user_location (user_id, branch, location),
  CONSTRAINT user_locations_ibfk_1 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS user_departments (
  id              INT NOT NULL AUTO_INCREMENT,
  user_id         INT NOT NULL,
  department_id   INT NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY unique_user_dept (user_id, department_id),
  CONSTRAINT user_departments_ibfk_1 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT user_departments_ibfk_2 FOREIGN KEY (department_id) REFERENCES departments (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS user_permissions (
  id            INT         NOT NULL AUTO_INCREMENT,
  user_id       INT         NOT NULL,
  module_name   VARCHAR(50) NOT NULL,
  can_read      TINYINT(1)  DEFAULT 0,
  can_create    TINYINT(1)  DEFAULT 0,
  can_update    TINYINT(1)  DEFAULT 0,
  can_delete    TINYINT(1)  DEFAULT 0,
  PRIMARY KEY (id),
  UNIQUE KEY unique_user_module (user_id, module_name),
  CONSTRAINT user_permissions_ibfk_1 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- 008_add_doctor_photo.sql
-- Add photo_url column only if it does not exist
-- Add column `photo_url` to `doctors` only if it does not exist (portable check)
SET @col_exists = (
  SELECT COUNT(*)
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'doctors' AND COLUMN_NAME = 'photo_url'
);
SET @sql = IF(@col_exists = 0,
  'ALTER TABLE doctors ADD COLUMN photo_url VARCHAR(255) NOT NULL',
  'SELECT "photo_url column exists"'
);
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- 009_add_indexes.sql (add indexes only when missing)
SET @idx_exists = (
  SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS
  WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'doctors' AND INDEX_NAME = 'department_id'
);
SET @sql = IF(@idx_exists = 0, 'ALTER TABLE doctors ADD INDEX department_id (department_id)', 'SELECT "index exists"');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @idx_exists = (
  SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS
  WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'roster' AND INDEX_NAME = 'employee_id'
);
SET @sql = IF(@idx_exists = 0, 'ALTER TABLE roster ADD INDEX employee_id (employee_id)', 'SELECT "index exists"');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @idx_exists = (
  SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS
  WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'user_departments' AND INDEX_NAME = 'department_id'
);
SET @sql = IF(@idx_exists = 0, 'ALTER TABLE user_departments ADD INDEX department_id (department_id)', 'SELECT "index exists"');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- 010_add_department_branch.sql
-- Add `branch` column to `departments` only if missing
SET @col_exists = (
  SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'departments' AND COLUMN_NAME = 'branch'
);
SET @sql = IF(@col_exists = 0, 'ALTER TABLE departments ADD COLUMN branch VARCHAR(50) DEFAULT NULL', 'SELECT "branch column exists"');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- 011_branch_department_doctor_redesign.sql
SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE IF NOT EXISTS branches (
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  branch_id int NOT NULL,
  location_id int NOT NULL,
  display_days json NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_doctor_sitting (employee_id, branch_id, location_id),
  KEY branch_id (branch_id),
  KEY location_id (location_id),
  CONSTRAINT doctor_sittings_ibfk_1 FOREIGN KEY (employee_id) REFERENCES doctors (employee_id) ON DELETE CASCADE,
  CONSTRAINT doctor_sittings_ibfk_2 FOREIGN KEY (branch_id) REFERENCES branches (id) ON DELETE CASCADE,
  CONSTRAINT doctor_sittings_ibfk_3 FOREIGN KEY (location_id) REFERENCES locations (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS doctor_sittings_new (
  id int NOT NULL AUTO_INCREMENT,
  employee_id varchar(50) NOT NULL,
  branch_id int NOT NULL,
  location_id int NOT NULL,
  display_days json NOT NULL,
  updated_at timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_doctor_sitting (employee_id, branch_id, location_id),
  KEY branch_id (branch_id),
  KEY location_id (location_id),
  CONSTRAINT doctor_sittings_new_ibfk_1 FOREIGN KEY (employee_id) REFERENCES doctors (employee_id) ON DELETE CASCADE,
  CONSTRAINT doctor_sittings_new_ibfk_2 FOREIGN KEY (branch_id) REFERENCES branches (id) ON DELETE CASCADE,
  CONSTRAINT doctor_sittings_new_ibfk_3 FOREIGN KEY (location_id) REFERENCES locations (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
INSERT IGNORE INTO branches (name)
INSERT IGNORE INTO doctor_sittings_new (employee_id, branch_id, location_id, display_days)
SELECT ds.employee_id, da.branch_id, da.location_id, ds.display_days
FROM doctor_sittings ds
JOIN doctors d ON d.employee_id = ds.employee_id
JOIN doctor_assignments da ON da.doctor_id = d.id;
SELECT DISTINCT branch FROM branches_locations;
DROP TABLE IF EXISTS doctor_sittings;
RENAME TABLE doctor_sittings_new TO doctor_sittings;

DELETE FROM branches WHERE name IN ('KIMS Bhubaneswar', 'KIMS Balasore', 'KIMS Cuttack', 'KIMS Berhampur');

CREATE TABLE IF NOT EXISTS locations (
  id INT NOT NULL AUTO_INCREMENT,
  branch_id INT NOT NULL,
  name VARCHAR(100) NOT NULL,
  status TINYINT(1) DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_branch_location (branch_id, name),
  CONSTRAINT fk_locations_branch FOREIGN KEY (branch_id) REFERENCES branches (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT IGNORE INTO locations (branch_id, name)
SELECT b.id, bl.location
FROM branches_locations bl
JOIN branches b ON bl.branch = b.name;

CREATE TABLE IF NOT EXISTS departments_new (
  id INT NOT NULL AUTO_INCREMENT,
  branch_id INT NOT NULL,
  location_id INT NOT NULL,
  name VARCHAR(100) NOT NULL,
  status TINYINT(1) DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_branch_location_dept (branch_id, location_id, name),
  CONSTRAINT fk_departments_branch FOREIGN KEY (branch_id) REFERENCES branches (id) ON DELETE CASCADE,
  CONSTRAINT fk_departments_location FOREIGN KEY (location_id) REFERENCES locations (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT IGNORE INTO departments_new (branch_id, location_id, name)
SELECT DISTINCT b.id, l.id, d.name
FROM doctors doc
JOIN departments d ON doc.department_id = d.id
JOIN branches b ON doc.branch = b.name
JOIN locations l ON (doc.location = l.name AND l.branch_id = b.id);

INSERT IGNORE INTO departments_new (branch_id, location_id, name)
SELECT DISTINCT (SELECT id FROM branches LIMIT 1), (SELECT id FROM locations LIMIT 1), d.name
FROM departments d
WHERE d.id NOT IN (SELECT DISTINCT department_id FROM doctors);

CREATE TABLE IF NOT EXISTS doctors_new (
  id              INT          NOT NULL AUTO_INCREMENT,
  employee_id     VARCHAR(50)  NOT NULL,
  name            VARCHAR(100) NOT NULL,
  designation     VARCHAR(100) NOT NULL,
  department_id   INT          NOT NULL,
  branch_id       INT          NOT NULL,
  location_id     INT          NOT NULL,
  photo_url       VARCHAR(255) NOT NULL,
  status          TINYINT(1)   DEFAULT 1,
  created_at      TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
  updated_at      TIMESTAMP    DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_branch_employee (branch_id, employee_id),
  KEY department_id (department_id),
  KEY location_id (location_id),
  CONSTRAINT fk_doctors_branch FOREIGN KEY (branch_id) REFERENCES branches (id) ON DELETE CASCADE,
  CONSTRAINT fk_doctors_location FOREIGN KEY (location_id) REFERENCES locations (id) ON DELETE CASCADE,
  CONSTRAINT fk_doctors_department FOREIGN KEY (department_id) REFERENCES departments_new (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT IGNORE INTO doctors_new (id, employee_id, name, designation, department_id, branch_id, location_id, photo_url, created_at)
SELECT doc.id, doc.employee_id, doc.name, doc.designation, dn.id, b.id, l.id, doc.photo_url, doc.created_at
FROM doctors doc
JOIN departments d ON doc.department_id = d.id
JOIN branches b ON doc.branch = b.name
JOIN locations l ON (doc.location = l.name AND l.branch_id = b.id)
JOIN departments_new dn ON (dn.name = d.name AND dn.branch_id = b.id AND dn.location_id = l.id);

DROP TABLE IF EXISTS roster;
DROP TABLE IF EXISTS user_departments;
DROP TABLE IF EXISTS doctors;
DROP TABLE IF EXISTS departments;

RENAME TABLE departments_new TO departments;
RENAME TABLE doctors_new TO doctors;

CREATE TABLE IF NOT EXISTS roster (
  id            INT          NOT NULL AUTO_INCREMENT,
  date          DATE         NOT NULL,
  doctor_id     INT          NOT NULL,
  timing        VARCHAR(100) NOT NULL,
  created_at    TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY unique_roster_entry (date, doctor_id),
  CONSTRAINT roster_ibfk_1 FOREIGN KEY (doctor_id) REFERENCES doctors (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS user_departments (
  id              INT NOT NULL AUTO_INCREMENT,
  user_id         INT NOT NULL,
  department_id   INT NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY unique_user_dept (user_id, department_id),
  CONSTRAINT user_departments_ibfk_1 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT user_departments_ibfk_2 FOREIGN KEY (department_id) REFERENCES departments (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS user_branches_new (
  id        INT NOT NULL AUTO_INCREMENT,
  user_id   INT NOT NULL,
  branch_id INT NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY unique_user_branch (user_id, branch_id),
  CONSTRAINT fk_user_branches_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT fk_user_branches_branch FOREIGN KEY (branch_id) REFERENCES branches (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT IGNORE INTO user_branches_new (user_id, branch_id)
SELECT ub.user_id, b.id
FROM user_branches ub
JOIN branches b ON ub.branch = b.name;

DROP TABLE IF EXISTS user_branches;
RENAME TABLE user_branches_new TO user_branches;

CREATE TABLE IF NOT EXISTS user_locations_new (
  id          INT NOT NULL AUTO_INCREMENT,
  user_id     INT NOT NULL,
  location_id INT NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY unique_user_location (user_id, location_id),
  CONSTRAINT fk_user_locations_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT fk_user_locations_location FOREIGN KEY (location_id) REFERENCES locations (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT IGNORE INTO user_locations_new (user_id, location_id)
SELECT ul.user_id, l.id
FROM user_locations ul
JOIN branches b ON ul.branch = b.name
JOIN locations l ON (ul.location = l.name AND l.branch_id = b.id);

DROP TABLE IF EXISTS user_locations;
RENAME TABLE user_locations_new TO user_locations;

DROP TABLE IF EXISTS branches_locations;

SET FOREIGN_KEY_CHECKS = 1;

-- 012_add_slugs_to_branches_locations.sql
SET FOREIGN_KEY_CHECKS = 0;
-- Add `slug` columns if missing and seed values
SET @col_exists = (
  SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'branches' AND COLUMN_NAME = 'slug'
);
SET @sql = IF(@col_exists = 0, 'ALTER TABLE branches ADD COLUMN slug VARCHAR(100) AFTER name', 'SELECT "branches.slug exists"');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @col_exists = (
  SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'locations' AND COLUMN_NAME = 'slug'
);
SET @sql = IF(@col_exists = 0, 'ALTER TABLE locations ADD COLUMN slug VARCHAR(100) AFTER name', 'SELECT "locations.slug exists"');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

UPDATE branches SET slug = LOWER(REPLACE(name, ' ', '-')) WHERE slug IS NULL;
UPDATE locations SET slug = LOWER(REPLACE(name, ' ', '-')) WHERE slug IS NULL;

-- Ensure non-null and unique constraint for location slugs
SET @sql = 'ALTER TABLE branches MODIFY COLUMN slug VARCHAR(100) NOT NULL';
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql = 'ALTER TABLE locations MODIFY COLUMN slug VARCHAR(100) NOT NULL';
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- Add unique index on (branch_id, slug) if missing
SET @idx_exists = (
  SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS
  WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'locations' AND INDEX_NAME = 'uniq_branch_location_slug'
);
SET @sql = IF(@idx_exists = 0, 'ALTER TABLE locations ADD UNIQUE KEY uniq_branch_location_slug (branch_id, slug)', 'SELECT "index exists"');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET FOREIGN_KEY_CHECKS = 1;

-- 013_create_playlist_tables.sql
SET FOREIGN_KEY_CHECKS = 0;
CREATE TABLE IF NOT EXISTS display_playlists (
  id INT NOT NULL AUTO_INCREMENT,
  screen_branch_id INT NOT NULL,
  screen_location_id INT NOT NULL,
  UNIQUE KEY uniq_screen (screen_branch_id, screen_location_id),
  PRIMARY KEY (id),
  CONSTRAINT fk_playlist_branch FOREIGN KEY (screen_branch_id) REFERENCES branches(id) ON DELETE CASCADE,
  CONSTRAINT fk_playlist_loc FOREIGN KEY (screen_location_id) REFERENCES locations(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS display_playlist_steps (
  id INT NOT NULL AUTO_INCREMENT,
  playlist_id INT NOT NULL,
  step_order INT NOT NULL,
  title VARCHAR(255) NOT NULL,
  duration_seconds INT NOT NULL DEFAULT 10,
  PRIMARY KEY (id),
  CONSTRAINT fk_step_playlist FOREIGN KEY (playlist_id) REFERENCES display_playlists(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS display_playlist_step_locations (
  step_id INT NOT NULL,
  location_id INT NOT NULL,
  PRIMARY KEY (step_id, location_id),
  CONSTRAINT fk_sl_step FOREIGN KEY (step_id) REFERENCES display_playlist_steps(id) ON DELETE CASCADE,
  CONSTRAINT fk_sl_loc FOREIGN KEY (location_id) REFERENCES locations(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS display_playlist_step_exclude_departments (
  step_id INT NOT NULL,
  department_id INT NOT NULL,
  PRIMARY KEY (step_id, department_id),
  CONSTRAINT fk_se_step FOREIGN KEY (step_id) REFERENCES display_playlist_steps(id) ON DELETE CASCADE,
  CONSTRAINT fk_se_dept FOREIGN KEY (department_id) REFERENCES departments(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

SET FOREIGN_KEY_CHECKS = 1;

-- 014_update_roster_schema.sql
SET FOREIGN_KEY_CHECKS = 0;
-- Add roster branch_id/location_id columns if missing
SET @col_exists = (
  SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'roster' AND COLUMN_NAME = 'branch_id'
);
SET @sql = IF(@col_exists = 0, 'ALTER TABLE roster ADD COLUMN branch_id INT AFTER doctor_id', 'SELECT "branch_id exists"');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @col_exists = (
  SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'roster' AND COLUMN_NAME = 'location_id'
);
SET @sql = IF(@col_exists = 0, 'ALTER TABLE roster ADD COLUMN location_id INT AFTER branch_id', 'SELECT "location_id exists"');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

UPDATE roster r
JOIN doctors d ON r.doctor_id = d.id
SET r.branch_id = d.branch_id, r.location_id = d.location_id
WHERE r.branch_id IS NULL;

ALTER TABLE roster MODIFY COLUMN branch_id INT NOT NULL;
ALTER TABLE roster MODIFY COLUMN location_id INT NOT NULL;

-- Add foreign keys only when missing
SET @fk_exists = (
  SELECT COUNT(*) FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS
  WHERE CONSTRAINT_SCHEMA = DATABASE() AND CONSTRAINT_NAME = 'fk_roster_branch'
);
SET @sql = IF(@fk_exists = 0, 'ALTER TABLE roster ADD CONSTRAINT fk_roster_branch FOREIGN KEY (branch_id) REFERENCES branches(id) ON DELETE CASCADE', 'SELECT "fk exists"');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @fk_exists = (
  SELECT COUNT(*) FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS
  WHERE CONSTRAINT_SCHEMA = DATABASE() AND CONSTRAINT_NAME = 'fk_roster_location'
);
SET @sql = IF(@fk_exists = 0, 'ALTER TABLE roster ADD CONSTRAINT fk_roster_location FOREIGN KEY (location_id) REFERENCES locations(id) ON DELETE CASCADE', 'SELECT "fk exists"');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- Drop unique index if exists, then create expected unique index (idempotent)
SET @idx_exists = (
  SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS
  WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'roster' AND INDEX_NAME = 'unique_roster_entry'
);
SET @sql = IF(@idx_exists > 0, 'ALTER TABLE roster DROP INDEX unique_roster_entry', 'SELECT "no index"');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @idx_exists = (
  SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS
  WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'roster' AND INDEX_NAME = 'unique_roster_entry'
);
SET @sql = IF(@idx_exists = 0, 'ALTER TABLE roster ADD UNIQUE KEY unique_roster_entry (date, doctor_id, branch_id, location_id, timing)', 'SELECT "index exists"');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET FOREIGN_KEY_CHECKS = 1;

-- 015_seed_pbmh_playlists.sql
SET @branch_name = 'PBMH';
SET @pbmh_id = (SELECT id FROM branches WHERE name = @branch_name LIMIT 1);
UPDATE locations SET slug = 'b-c-block' WHERE name = 'B/C Block' AND branch_id = @pbmh_id;
SET @loc_a_id = (SELECT id FROM locations WHERE branch_id = @pbmh_id AND name = 'A Block' LIMIT 1);
SET @loc_bc_id = (SELECT id FROM locations WHERE branch_id = @pbmh_id AND name = 'B/C Block' LIMIT 1);
INSERT IGNORE INTO display_playlists (screen_branch_id, screen_location_id) VALUES (@pbmh_id, @loc_a_id);
INSERT IGNORE INTO display_playlists (screen_branch_id, screen_location_id) VALUES (@pbmh_id, @loc_bc_id);
SET @playlist_a_id = (SELECT id FROM display_playlists WHERE screen_branch_id = @pbmh_id AND screen_location_id = @loc_a_id LIMIT 1);
SET @playlist_bc_id = (SELECT id FROM display_playlists WHERE screen_branch_id = @pbmh_id AND screen_location_id = @loc_bc_id LIMIT 1);
DELETE FROM display_playlist_steps WHERE playlist_id IN (@playlist_a_id, @playlist_bc_id);
INSERT INTO display_playlist_steps (playlist_id, step_order, title, duration_seconds) 
VALUES (@playlist_a_id, 1, 'A Block', 10);
SET @step_a_id = LAST_INSERT_ID();
INSERT INTO display_playlist_step_locations (step_id, location_id) VALUES (@step_a_id, @loc_a_id);
INSERT INTO display_playlist_steps (playlist_id, step_order, title, duration_seconds) 
VALUES (@playlist_bc_id, 1, 'B/C Block', 10);
SET @step_bc_id = LAST_INSERT_ID();
INSERT INTO display_playlist_step_locations (step_id, location_id) VALUES (@step_bc_id, @loc_bc_id);
INSERT IGNORE INTO departments (branch_id, location_id, name) VALUES (@pbmh_id, @loc_bc_id, 'Emergency Medicine');
SET @em_dept_id = (SELECT id FROM departments WHERE name = 'Emergency Medicine' AND branch_id = @pbmh_id AND location_id = @loc_bc_id LIMIT 1);
INSERT IGNORE INTO display_playlist_step_exclude_departments (step_id, department_id)
SELECT @step_bc_id, id FROM departments WHERE name = 'Emergency Medicine' AND (branch_id = @pbmh_id OR branch_id IS NULL);

-- 016_normalize_doctor_master.sql
SET FOREIGN_KEY_CHECKS = 0;
CREATE TABLE IF NOT EXISTS doctor_assignments (
  id INT NOT NULL AUTO_INCREMENT,
  doctor_id INT NOT NULL,
  branch_id INT NOT NULL,
  location_id INT NOT NULL,
  department_id INT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_doctor_assignment (doctor_id, branch_id, location_id, department_id),
  CONSTRAINT fk_assign_doctor FOREIGN KEY (doctor_id) REFERENCES doctors (id) ON DELETE CASCADE,
  CONSTRAINT fk_assign_branch FOREIGN KEY (branch_id) REFERENCES branches (id) ON DELETE CASCADE,
  CONSTRAINT fk_assign_location FOREIGN KEY (location_id) REFERENCES locations (id) ON DELETE CASCADE,
  CONSTRAINT fk_assign_department FOREIGN KEY (department_id) REFERENCES departments (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT IGNORE INTO doctor_assignments (doctor_id, branch_id, location_id, department_id)
SELECT id, branch_id, location_id, department_id FROM doctors;

CREATE TEMPORARY TABLE IF NOT EXISTS doc_mapping AS
SELECT d.id AS old_id, (SELECT MIN(id) FROM doctors d2 WHERE d2.employee_id = d.employee_id) AS new_id
FROM doctors d;

UPDATE doctor_assignments da
JOIN doc_mapping dm ON da.doctor_id = dm.old_id
SET da.doctor_id = dm.new_id;

UPDATE roster r
JOIN doc_mapping dm ON r.doctor_id = dm.old_id
SET r.doctor_id = dm.new_id;

DELETE FROM doctors WHERE id NOT IN (SELECT new_id FROM doc_mapping);

-- Drop foreign keys on doctors only if they exist
SET @fk_exists = (
  SELECT COUNT(*) FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS
  WHERE CONSTRAINT_SCHEMA = DATABASE() AND CONSTRAINT_NAME = 'fk_doctors_branch'
);
SET @sql = IF(@fk_exists > 0, 'ALTER TABLE doctors DROP FOREIGN KEY fk_doctors_branch', 'SELECT "no fk"');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @fk_exists = (
  SELECT COUNT(*) FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS
  WHERE CONSTRAINT_SCHEMA = DATABASE() AND CONSTRAINT_NAME = 'fk_doctors_location'
);
SET @sql = IF(@fk_exists > 0, 'ALTER TABLE doctors DROP FOREIGN KEY fk_doctors_location', 'SELECT "no fk"');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @fk_exists = (
  SELECT COUNT(*) FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS
  WHERE CONSTRAINT_SCHEMA = DATABASE() AND CONSTRAINT_NAME = 'fk_doctors_department'
);
SET @sql = IF(@fk_exists > 0, 'ALTER TABLE doctors DROP FOREIGN KEY fk_doctors_department', 'SELECT "no fk"');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- Drop indexes if they exist
SET @idx_exists = (
  SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS
  WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'doctors' AND INDEX_NAME = 'uniq_branch_employee'
);
SET @sql = IF(@idx_exists > 0, 'ALTER TABLE doctors DROP INDEX uniq_branch_employee', 'SELECT "no index"');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @idx_exists = (
  SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS
  WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'doctors' AND INDEX_NAME = 'department_id'
);
SET @sql = IF(@idx_exists > 0, 'ALTER TABLE doctors DROP INDEX department_id', 'SELECT "no index"');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @idx_exists = (
  SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS
  WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'doctors' AND INDEX_NAME = 'location_id'
);
SET @sql = IF(@idx_exists > 0, 'ALTER TABLE doctors DROP INDEX location_id', 'SELECT "no index"');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

ALTER TABLE doctors ADD UNIQUE KEY uniq_employee_id (employee_id);

-- Drop columns only if they exist
SET @col_exists = (
  SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'doctors' AND COLUMN_NAME = 'branch_id'
);
SET @sql = IF(@col_exists > 0, 'ALTER TABLE doctors DROP COLUMN branch_id', 'SELECT "no column"');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @col_exists = (
  SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'doctors' AND COLUMN_NAME = 'location_id'
);
SET @sql = IF(@col_exists > 0, 'ALTER TABLE doctors DROP COLUMN location_id', 'SELECT "no column"');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @col_exists = (
  SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'doctors' AND COLUMN_NAME = 'department_id'
);
SET @sql = IF(@col_exists > 0, 'ALTER TABLE doctors DROP COLUMN department_id', 'SELECT "no column"');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET FOREIGN_KEY_CHECKS = 1;

-- 018_make_doctor_photo_optional.sql (normalized)
ALTER TABLE doctors MODIFY photo_url VARCHAR(255) NULL;

-- 019_add_shift_time_to_doctor_assignments.sql
-- Add shift_time to doctor_assignments if missing
SET @col_exists = (
  SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'doctor_assignments' AND COLUMN_NAME = 'shift_time'
);
SET @sql = IF(@col_exists = 0, 'ALTER TABLE doctor_assignments ADD COLUMN shift_time VARCHAR(100) DEFAULT NULL AFTER department_id', 'SELECT "shift_time exists"');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- 020_sync_internal_tables.sql
SET FOREIGN_KEY_CHECKS = 0;

-- Table structure for branch_designations
CREATE TABLE IF NOT EXISTS branch_designations (
  id int NOT NULL AUTO_INCREMENT,
  branch_id int NOT NULL,
  designation varchar(100) NOT NULL,
  sort_order int NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  KEY branch_id_idx (branch_id),
  CONSTRAINT branch_designations_ibfk_1 FOREIGN KEY (branch_id) REFERENCES branches (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Table structure for department_designations
CREATE TABLE IF NOT EXISTS department_designations (
  id int NOT NULL AUTO_INCREMENT,
  department_id int NOT NULL,
  designation varchar(100) NOT NULL,
  sort_order int NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY dept_desig (department_id, designation),
  CONSTRAINT department_designations_ibfk_1 FOREIGN KEY (department_id) REFERENCES departments (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Table structure for doctor_branch_location
CREATE TABLE IF NOT EXISTS doctor_branch_location (
  doctor_id int NOT NULL,
  branch_id int NOT NULL,
  location_id int NOT NULL,
  PRIMARY KEY (doctor_id, branch_id, location_id),
  KEY fk_dbl_branch (branch_id),
  KEY fk_dbl_location (location_id),
  CONSTRAINT fk_dbl_branch FOREIGN KEY (branch_id) REFERENCES branches (id) ON DELETE CASCADE,
  CONSTRAINT fk_dbl_doctor FOREIGN KEY (doctor_id) REFERENCES doctors (id) ON DELETE CASCADE,
  CONSTRAINT fk_dbl_location FOREIGN KEY (location_id) REFERENCES locations (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Table structure for doctor_departments
CREATE TABLE IF NOT EXISTS doctor_departments (
  doctor_id int NOT NULL,
  department_id int NOT NULL,
  PRIMARY KEY (doctor_id, department_id),
  KEY fk_dd_department (department_id),
  CONSTRAINT fk_dd_department FOREIGN KEY (department_id) REFERENCES departments (id) ON DELETE CASCADE,
  CONSTRAINT fk_dd_doctor FOREIGN KEY (doctor_id) REFERENCES doctors (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Table structure for doctor_sittings
CREATE TABLE IF NOT EXISTS doctor_sittings (
  id int NOT NULL AUTO_INCREMENT,
  employee_id varchar(50) NOT NULL,
  display_days json NOT NULL,
  updated_at timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY employee_id (employee_id),
  CONSTRAINT doctor_sittings_ibfk_1 FOREIGN KEY (employee_id) REFERENCES doctors (employee_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Table structure for videos
CREATE TABLE IF NOT EXISTS videos (
  id int NOT NULL AUTO_INCREMENT,
  title varchar(255) DEFAULT NULL,
  branch_id int NOT NULL,
  location_id int NOT NULL,
  file_path varchar(255) NOT NULL,
  original_name varchar(255) NOT NULL,
  file_size int NOT NULL,
  duration float NOT NULL,
  uploaded_by int DEFAULT NULL,
  created_at timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  play_order int DEFAULT 1,
  PRIMARY KEY (id),
  KEY location_id_idx (location_id),
  KEY uploaded_by_idx (uploaded_by),
  KEY branch_id_idx (branch_id),
  CONSTRAINT videos_ibfk_1 FOREIGN KEY (branch_id) REFERENCES branches (id) ON DELETE CASCADE,
  CONSTRAINT videos_ibfk_2 FOREIGN KEY (location_id) REFERENCES locations (id) ON DELETE CASCADE,
  CONSTRAINT videos_ibfk_3 FOREIGN KEY (uploaded_by) REFERENCES users (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

SET FOREIGN_KEY_CHECKS = 1;

-- 021_seed_core_hierarchy.sql
-- Seed script for core hierarchy data

-- Branches
INSERT IGNORE INTO branches (`id`, `name`, `status`, `created_at`, `updated_at`) VALUES
  (1, 'PBMH', 1, '2026-07-20 09:02:43', '2026-07-20 09:02:43'),
  (2, 'SSCC', 1, '2026-07-20 09:02:43', '2026-07-20 09:55:06'),
  (3, 'KIDS', 1, '2026-07-20 09:02:43', '2026-07-20 11:19:11');

-- Branch Designations
CREATE TABLE IF NOT EXISTS branch_designations (
  id int NOT NULL AUTO_INCREMENT,
  branch_id int NOT NULL,
  designation varchar(100) NOT NULL,
  sort_order int NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_branch_designation (branch_id, designation),
  KEY branch_id_idx (branch_id),
  CONSTRAINT branch_designations_ibfk_1 FOREIGN KEY (branch_id) REFERENCES branches (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

SET @idx_exists = (
  SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS
  WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'branch_designations' AND INDEX_NAME = 'uniq_branch_designation'
);
SET @sql = IF(@idx_exists = 0, 'ALTER TABLE branch_designations ADD UNIQUE KEY uniq_branch_designation (branch_id, designation)', 'SELECT "index exists"');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

INSERT IGNORE INTO branch_designations (branch_id, designation, sort_order)
SELECT b.id, x.designation, x.sort_order
FROM branches b
JOIN (
  SELECT 'PBMH' AS branch_name, 'HEAD OF THE DEPT' AS designation, 1 AS sort_order UNION ALL
  SELECT 'PBMH', 'HEAD OF THE DEPT / UNIT HEAD', 2 UNION ALL
  SELECT 'PBMH', 'PROFESSOR', 3 UNION ALL
  SELECT 'PBMH', 'ASSOCIATE PROFESSOR', 4 UNION ALL
  SELECT 'PBMH', 'ASSISTANT PROFESSOR', 5 UNION ALL
  SELECT 'PBMH', 'SENIOR RESIDENT', 6 UNION ALL
  SELECT 'PBMH', 'CONSULTANT', 7 UNION ALL
  SELECT 'PBMH', 'SENIOR CONSULTANT', 8 UNION ALL
  SELECT 'PBMH', 'VISITING CONSULTANT', 9 UNION ALL
  SELECT 'PBMH', 'VISITING PROFESSOR', 10 UNION ALL
  SELECT 'SSCC', 'SENIOR CONSULTANT', 1 UNION ALL
  SELECT 'SSCC', 'CONSULTANT', 2 UNION ALL
  SELECT 'SSCC', 'ASSOCIATE PROFESSOR', 3 UNION ALL
  SELECT 'SSCC', 'PROFESSOR', 4 UNION ALL
  SELECT 'SSCC', 'VISITING CONSULTANT', 5 UNION ALL
  SELECT 'SSCC', 'EMERITUS PROFESSOR', 6 UNION ALL
  SELECT 'SSCC', 'ASSISTANT PROFESSOR', 7 UNION ALL
  SELECT 'SSCC', 'SENIOR RESIDENT', 8 UNION ALL
  SELECT 'SSCC', 'VISITING PROFESSOR', 9 UNION ALL
  SELECT 'KIDS', 'PROFESSOR', 1 UNION ALL
  SELECT 'KIDS', 'ASSOCIATE PROFESSOR', 2 UNION ALL
  SELECT 'KIDS', 'ASSISTANT PROFESSOR', 3 UNION ALL
  SELECT 'KIDS', 'SENIOR RESIDENT', 4 UNION ALL
  SELECT 'KIDS', 'CONSULTANT', 5 UNION ALL
  SELECT 'KIDS', 'SENIOR CONSULTANT', 6 UNION ALL
  SELECT 'KIDS', 'VISITING CONSULTANT', 7 UNION ALL
  SELECT 'KIDS', 'VISITING PROFESSOR', 8
) x ON UPPER(b.name) = x.branch_name;

-- Locations
INSERT IGNORE INTO locations (`id`, `name`, `branch_id`, `status`, `created_at`, `updated_at`) VALUES
  (1, 'A BLOCK', 1, 1, '2026-07-20 09:02:43', '2026-07-20 09:02:43'),
  (2, 'B&C (MB) BLOCK', 1, 1, '2026-07-20 09:02:43', '2026-07-20 09:02:43'),
  (3, 'KSS', 2, 1, '2026-07-20 09:02:43', '2026-07-20 09:02:43'),
  (4, 'KCC', 2, 1, '2026-07-20 09:02:43', '2026-07-20 09:02:43'),
  (5, 'DENTAL', 3, 1, '2026-07-20 09:02:43', '2026-07-20 09:02:43');

-- Departments
INSERT IGNORE INTO departments (`id`, `name`, `branch_id`, `location_id`, `status`, `created_at`, `updated_at`) VALUES
  (1, 'OBSTETRICS AND GYNAECOLOGY', 1, 1, 1, '2026-07-20 09:02:43', '2026-07-20 09:02:43'),
  (2, 'OPHTHALMOLOGY', 1, 1, 1, '2026-07-20 09:02:43', '2026-07-20 09:02:43'),
  (3, 'DERMATOLOGY', 2, 3, 1, '2026-07-20 09:02:43', '2026-07-26 06:15:41'),
  (4, 'PAEDIATRICS', 1, 1, 1, '2026-07-20 09:02:43', '2026-07-20 09:02:43'),
  (5, 'PAEDIATRIC SURGERY', 1, 1, 1, '2026-07-20 09:02:43', '2026-07-20 09:02:43'),
  (6, 'RETINA CLINIC', 1, 1, 1, '2026-07-20 09:02:43', '2026-07-20 09:02:43'),
  (7, 'NEONATOLOGY', 1, 1, 1, '2026-07-20 09:02:43', '2026-07-20 09:02:43'),
  (8, 'REPRODUCTIVE MEDICINE', 1, 1, 1, '2026-07-20 09:02:43', '2026-07-20 09:02:43'),
  (9, 'NEUROSURGERY', 1, 2, 1, '2026-07-20 09:02:43', '2026-07-20 09:02:43'),
  (10, 'GENERAL MEDICINE', 1, 2, 1, '2026-07-20 09:02:43', '2026-07-20 09:02:43'),
  (11, 'MEDICAL GASTROENTEROLOGY', 1, 2, 1, '2026-07-20 09:02:43', '2026-07-20 09:02:43'),
  (12, 'GENERAL SURGERY', 1, 2, 1, '2026-07-20 09:02:43', '2026-07-20 09:02:43'),
  (13, 'ORTHOPAEDICS', 1, 2, 1, '2026-07-20 09:02:43', '2026-07-20 09:02:43'),
  (14, 'UROLOGY', 1, 2, 1, '2026-07-20 09:02:43', '2026-07-20 09:02:43'),
  (15, 'ENDOCRINOLOGY', 1, 2, 1, '2026-07-20 09:02:43', '2026-07-20 09:02:43'),
  (16, 'CARDIOTHORACIC AND VASCULAR SURGERY', 1, 2, 1, '2026-07-20 09:02:43', '2026-07-20 09:02:43'),
  (17, 'NEUROLOGY', 1, 2, 1, '2026-07-20 09:02:43', '2026-07-20 09:02:43'),
  (18, 'CARDIOLOGY', 1, 2, 1, '2026-07-20 09:02:43', '2026-07-20 09:02:43'),
  (19, 'CLINICAL IMMUNOLOGY AND RHEUMATOLOGY', 1, 2, 1, '2026-07-20 09:02:43', '2026-07-20 09:02:43'),
  (20, 'ENT', 1, 2, 1, '2026-07-20 09:02:43', '2026-07-20 11:50:15'),
  (21, 'PULMONARY MEDICINE', 1, 2, 1, '2026-07-20 09:02:43', '2026-07-20 09:02:43'),
  (22, 'PLASTIC SURGERY', 1, 2, 1, '2026-07-20 09:02:43', '2026-07-20 09:02:43'),
  (23, 'PSYCHIATRY', 1, 2, 1, '2026-07-20 09:02:43', '2026-07-20 09:02:43'),
  (24, 'HAEMATOLOGY', 1, 2, 1, '2026-07-20 09:02:43', '2026-07-20 09:02:43'),
  (25, 'NEPHROLOGY', 1, 2, 1, '2026-07-20 09:02:43', '2026-07-20 09:02:43'),
  (26, 'SURGICAL GASTROENTEROLOGY', 1, 2, 1, '2026-07-20 09:02:43', '2026-07-20 09:02:43'),
  (27, 'ENDOCRINE AND BREAST SURGERY', 1, 2, 1, '2026-07-20 09:02:43', '2026-07-20 09:02:43'),
  (28, 'HAEMATOLOGY', 2, 3, 1, '2026-07-20 09:02:43', '2026-07-20 09:02:43'),
  (29, 'NEPHROLOGY', 2, 3, 1, '2026-07-20 09:02:43', '2026-07-20 09:02:43'),
  (30, 'NEUROSURGERY', 2, 3, 1, '2026-07-20 09:02:43', '2026-07-20 09:02:43'),
  (31, 'PULMONARY MEDICINE', 2, 3, 1, '2026-07-20 09:02:43', '2026-07-20 09:02:43'),
  (32, 'ORTHOPAEDICS', 2, 3, 1, '2026-07-20 09:02:43', '2026-07-20 09:02:43'),
  (33, 'NEUROLOGY', 2, 3, 1, '2026-07-20 09:02:43', '2026-07-20 09:02:43'),
  (34, 'GENERAL MEDICINE', 2, 3, 1, '2026-07-20 09:02:43', '2026-07-23 05:51:59'),
  (35, 'CARDIOTHORACIC AND VASCULAR SURGERY', 2, 3, 1, '2026-07-20 09:02:43', '2026-07-20 09:02:43'),
  (36, 'PLASTIC SURGERY', 2, 3, 1, '2026-07-20 09:02:43', '2026-07-20 09:02:43'),
  (37, 'ENDOCRINOLOGY', 2, 3, 1, '2026-07-20 09:02:43', '2026-07-20 09:02:43'),
  (38, 'CARDIOLOGY', 2, 3, 1, '2026-07-20 09:02:43', '2026-07-26 06:15:39'),
  (39, 'UROLOGY', 2, 3, 1, '2026-07-20 09:02:43', '2026-07-20 09:02:43'),
  (40, 'SPINE AND ORTHO SURGERY', 2, 3, 1, '2026-07-20 09:02:43', '2026-07-20 09:02:43'),
  (41, 'GENERAL SURGERY', 2, 3, 1, '2026-07-20 09:02:43', '2026-07-26 14:28:39'),
  (42, 'OPHTHALMOLOGY', 2, 3, 1, '2026-07-20 09:02:43', '2026-07-20 09:02:43'),
  (43, 'CLINICAL IMMUNOLOGY AND RHEUMATOLOGY', 2, 3, 1, '2026-07-20 09:02:43', '2026-07-20 09:02:43'),
  (44, 'PSYCHIATRY', 2, 3, 1, '2026-07-20 09:02:43', '2026-07-20 09:02:43'),
  (45, 'OBSTETRICS AND GYNAECOLOGY', 2, 3, 1, '2026-07-20 09:02:43', '2026-07-20 09:02:43'),
  (46, 'MEDICAL ONCOLOGY', 2, 4, 1, '2026-07-20 09:02:43', '2026-07-20 09:02:43'),
  (47, 'RADIATION ONCOLOGY', 2, 4, 1, '2026-07-20 09:02:43', '2026-07-20 09:02:43'),
  (48, 'SURGICAL ONCOLOGY', 2, 4, 1, '2026-07-20 09:02:43', '2026-07-20 09:02:43'),
  (49, 'MEDICAL GASTROENTEROLOGY', 2, 4, 1, '2026-07-20 09:02:43', '2026-07-20 09:02:43'),
  (50, 'EAR NOSE AND THROAT', 2, 4, 1, '2026-07-20 09:02:43', '2026-07-20 09:02:43'),
  (51, 'SURGICAL GASTROENTEROLOGY', 2, 4, 1, '2026-07-20 09:02:43', '2026-07-20 09:02:43'),
  (52, 'ORAL MEDICINE AND RADIOLOGY', 3, 5, 1, '2026-07-20 09:02:43', '2026-07-20 09:02:43'),
  (53, 'PAEDIATRIC AND PREVENTIVE DENTISTRY', 3, 5, 1, '2026-07-20 09:02:43', '2026-07-20 09:02:43'),
  (54, 'ORAL AND MAXILLOFACIAL SURGERY', 3, 5, 1, '2026-07-20 09:02:43', '2026-07-20 09:02:43'),
  (55, 'ORAL PATHOLOGY AND MICROBIOLOGY', 3, 5, 1, '2026-07-20 09:02:43', '2026-07-20 09:02:43'),
  (56, 'PERIODONTOLOGY', 3, 5, 1, '2026-07-20 09:02:43', '2026-07-20 09:02:43'),
  (57, 'PROSTHODONTICS AND CROWN AND BRIDGE', 3, 5, 1, '2026-07-20 09:02:43', '2026-07-20 09:02:43'),
  (58, 'ORTHODONTICS AND DENTOFACIAL ORTHOPAEDICS', 3, 5, 1, '2026-07-20 09:02:43', '2026-07-20 09:02:43'),
  (59, 'CONSERVATIVE DENTISTRY AND ENDODONTICS', 3, 5, 1, '2026-07-20 09:02:43', '2026-07-20 09:02:43'),
  (60, 'PUBLIC HEALTH DENTISTRY', 3, 5, 1, '2026-07-20 09:02:43', '2026-07-20 09:02:43'),
  (61, 'DERMATOLOGY', 1, 1, 1, '2026-07-20 10:26:44', '2026-07-20 10:26:44'),
  (62, 'CARDIOLOGY', 1, 1, 1, '2026-07-20 10:55:06', '2026-07-26 06:15:39'),
  (63, 'CARDIOLOGY', 2, 4, 0, '2026-07-20 10:57:16', '2026-08-06 09:58:20'),
  (64, 'GENERAL SURGERY', 2, 4, 1, '2026-07-22 05:09:46', '2026-07-29 11:45:59');

-- Branch Designations
-- Department Designations

-- End of combined migrations
